### ISSUE TITLE
cave generator is broken with mc 1.7.10

### ISSUE THREAD

**Issue by petrukhnov** [Ted80-Minecraft-Mods/Better-World-Generation-4#20]
Other generators seemed to work fine. I used only forge and BWG4 plugins in single player. World generated, but can't be 

Time: 5.7.2014 20:31
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.world.World.func_82732_R()Lnet/minecraft/util/Vec3Pool;
    at bwg4.api.gen.GeneratorTypeCaveSurvival.getFogColor(GeneratorTypeCaveSurvival.java:62)
    at bwg4.world.ProviderBWG4.func_76562_b(ProviderBWG4.java:131)
    at net.minecraft.world.World.func_72948_g(World.java:1681)
    at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1676)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1154)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Affected level --
Details:
    Level name: MpServer
    Chunk stats: MultiplayerChunkCache: 30, 30
    Level seed: 0
    Level generator: ID 04 - BWG4, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 5 game time, 5 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Minecraft Version: 1.7.10
FML: MCP v9.05 FML v7.10.1.1160 Minecraft Forge 10.13.0.1160 4 mods loaded, 4 mods active
mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
FML{7.10.1.1160} [Forge Mod Loader](forge-1.7.10-10.13.0.1160.jar) 
Forge{10.13.0.1160} [Minecraft Forge](forge-1.7.10-10.13.0.1160.jar) 
BWG4{1.2.0g} [Better World Generation 4](BWG4-1.2.0g.jar) 
Launched Version: 1.7.10-Forge10.13.0.1160
LWJGL: 2.9.1

**Comment by ted80** [comment]
bwg4 has not yet been updated to 1.7.10
